IBM/couchbackup

CHANGES.md, app.js, citest/test.js
Related to #61, this PR addresses cases where we're writing to a stream and not a file, so it's not possible to check if it is writable before starting. Instead, make sure that the callback is called with the correct error
=> Throw error when write fails

Jenkinsfile, citest/citestutils.js, citest/test.js, citest/toxy.js
Add following poisons to toxy tests:
- bandwidth-limit
- latency
- slow-read
The remaining poisons (namely `abort`, `rate-limit` & `unexpected-errors`) will be implemented in a future PR as additional retrying logic is required.
_'[test] make test release build' commit to be removed prior to merge._
Uncomment poisons and introduce TEST_TIMEOUT_MULTIPLIER to ensure toxy tests don't timeout.
Fixes #79.
=> 79 fix unreliable network tests

examples/s3-backup-stream.js
This was remanent from a very basic feature I used in my own backup
scripts to clean up old backups. However, it wasn't at all suitable
for wider use.
#98
=> Remove retain argument in s3-backup-stream.js

CHANGES.md, app.js, includes/error.js, includes/restore.js, includes/writer.js
See #22 
**What**
Abort processing for fatal errors when doing restore:
- Throw fatal error if the candidate restore database doesn't exist (HEAD returns 404)
- Throw fatal error if unexpected return code is obtained after doing HEAD on candidate restore database
- Throw fatal error if a 401 is encountered when trying to write to the database
- Stop processing queue and other threads if fatal errors are encountered
**How**
Make `writer` emit `error` events and then call the error callback as appropriate.
Make `exists` more robust.
**Testing**
Manual testing restoring to a database without `_writer` permissions:
```
$ COUCH_URL=https://tomblench.cloudant.com COUCH_DATABASE=airportdb_backup  ./bin/couchrestore.bin.js < out 
...
Database https://tomblench.cloudant.com/airportdb_backup does …
```
=> Improve error handling

app.js, includes/backup.js, includes/error.js, includes/spoolchanges.js
Terminate on spool changes failure, for example:
```
$ couchbackup --url http://localhost:3000/ --db animaldb
================================================================================
Performing backup on http://localhost:3000/animaldb using configuration:
{
"bufferSize": 500,
"log": "/var/folders/5p/11lmsvwn5l91cn7ysrs4nm1r0000gn/T/tmp-79048fCiWkfAJefLd.tmp",
"mode": "full",
"parallelism": 5
}
================================================================================
Changes request failed with status code 500
$ echo $?
30
```
Ensure `resp.statusCode == 200` prior to processing changes body.
Fixes #103.
=> Terminate on spool changes failure

CHANGES.md, includes/backup.js, includes/error.js, includes/request.js, includes/restore.js, includes/shallowbackup.js, includes/spoolchanges.js, includes/writer.js, package.json, test/request.js
Use newly added `request.isOK` & `request.isFatal` HTTP status code validators anywhere we validate HTTP response codes.
Add HTTP status code validators to `request.js`. 
- `request.isFatal` will return a new `HTTPFatalError` error on failure that will terminate the CLI.
- `request.isOK` will return a new `HTTPError` error on failure that logs an error with the event emitter.
Fixes #115 and is closely related to #32.
=> 115 validate writer requests

test/ci_encryption.js, test/citestutils.js
Added test for encrypting content via openssl
* Added new ci_encryption.js test file.
* Added to test utilities to support encryption.
Note supports CLI only and gzip/encryption can only be used independently in tests.
New test addition only.
=> Added backup and restore via openssl encryption

README.md, app.js, bin/couchbackup.bin.js, includes/backup.js, includes/restore.js, includes/spoolchanges.js, includes/writer.js, test/citestutils.js
Remove stderr logging from library.
Ensure all errors are passed via the event emitter to the listening client rather than being printed directly to stderr.
See #32.
=> Remove stderr logging from library

app.js, includes/backup.js, includes/error.js, includes/spoolchanges.js, includes/writer.js, test/app.js, test/spoolchanges.js
Handle fatal errors in `spoolchanges.js`.
- Add new `error` listener for change request.
- Invert error property `.isFatal` to `.isTransient` to ensure all unhandled errors are fatal.
Includes additional unit tests.
Fixes #135.
=> 135 handle spool changes errors

includes/shallowbackup.js, test/fixtures/animaldb_all_docs_1.json, test/fixtures/animaldb_all_docs_2.json, test/fixtures/animaldb_all_docs_3.json, test/fixtures/animaldb_all_docs_4.json, test/shallowbackup.js
Handle fatal errors in shallow backup.
Use `request.checkResponseAndCallbackError` to check `/_all_docs` responses. If fatal, terminate the backup and emit an error.
Includes additional unit tests.
The commented test requires https://github.com/cloudant/couchbackup/tree/22-permanent-errors.
Fixes #128.
=> 128 handle fatal errors in shallow backup

includes/restore.js, includes/writer.js, test/citestutils.js, test/fatalerrors.js
What was changed, e.g.
>Added support for incremental backup mode
After #133 merged there were some problems with multiple callbacks for multiple queue tasks failing with HTTP errors on restore.
Used the event emitter to emit `error` instead of calling back with an error to the `_transform` method's `done` callback, because that would already get called when the docs were pushed to the queue, and then get called again if an error happened.
Note `CHANGES` already updated under #133 
Added new test `should terminate on multiple _bulk_docs HTTPFatalError` that uses a `bufferSize: 1` to ensure multiple queue tasks will fail to cover this branch.
Additional impact from #22
=> 22 restore multiple fatal

CHANGES.md, app.js, includes/restore.js, includes/writer.js, test/citestutils.js, test/fatalerrors.js
Fixed uncaught `readstream.destroy is not a function` error.
Called destroy only if it is available on the stream
*  Added check for `destroy()` function existence before calling.
* Added check for fatal `didError` flag in writer loop.
Moved restore error handling into `app.js` to benefit from existing
one call functionality.
Updated `removeListeners` call to remove only the error listeners.
Added test for terminating a larger stream 
* Added an `InfiniteBackupStream` to avoid the whole stream having already been consumed by the test.
* Made `multiple fatal _bulk_docs error` test run for API only since the number of calls cannot be guaranteed for CLI case.
* Added parallelism arg to restore test utility. …
=> 147 restore error

CHANGES.md, includes/writer.js, test/fatalerrors.js
Added support for compressing _bulk_docs request bodies.
Changed from `db.bulk` to a custom `_bulk_docs` request.
Added `gzip` `Content-Encoding` header.
Compressed the docs `payload` content using `zlib.createGzip()` and streaming the content through it.
No new tests added, the restore requests are well exercised by the existing automated tests and those are passing.
I manually verified that the content length is smaller for requests using this branch.
Fixes #54
=> Added gzip for restore _bulk_docs POST

CHANGES.md, README.md, app.js, includes/backup.js, includes/error.js, includes/request.js, includes/restore.js, includes/shallowbackup.js, includes/spoolchanges.js, includes/writer.js, test/app.js, test/request.js, test/shallowbackup.js, test/spoolchanges.js, test/writer.js
Changed retry logic to nodejs-cloudant.
Instead of handling retries internally, delegate to nodejs-cloudant's `retry` plugin.
i) Configured `retry` plugin.
ii) Removed transient `HTTPError` errors and associated events.
iii) Updated `README` for errors no longer being emitted.
*For consideration by reviewers*
The couchbackup API no longer emits `error` events for transient errors. It could be argued that this is a breaking change, but the previous code and this new version both retry the transient error anyway. It's possible (but doubtful given the lack of a functioning cancellation API) that users were cancelling backups on transient errors, which would not longer be possible.
iv) Updated tests for …
=> Changed retry logic to nodejs-cloudant

CHANGES.md, package.json
- [NEW] Added API for upcoming IBM Cloud Identity and Access Management support
for Cloudant on IBM Cloud. Note: IAM API key support is not yet enabled in the
service.
- [IMPROVED] Enhanced resilience of backup and restore processes by enabling the
nodejs-cloudant retry plugin.
- [IMPROVED] Added URL validation for presence of host and database elements.
- [UPGRADED] Increased nodejs-cloudant dependency to 2.x.  
Also pinned `eslint-config-standard` for #189 
No new tests, proposed release.
2.1.0 release https://github.com/cloudant/couchbackup/milestone/4
&
fixes #189
=> Prepare v2.1.0

CHANGES.md, includes/spoolchanges.js, package.json
Fix failure to decompress a gzipped `/_changes` response.
_TODO: Bump @cloudant/cloudant dependancy following release of `2.1.0`._
Fixes #196.
=> Fix failure to decompress a gzipped /_changes response

CHANGES.md, package.json
- [FIXED] An issue where the _changes response stream doesn't get correctly decompressed.
- [FIXED] Prevent duplicate execution of backup error callbacks.
- [NOTE] Update engines in preparation for Node.js 4 “Argon” end-of-life.
=> Prepare 2.2.0 release

CHANGES.md, app.js, includes/writer.js, test/ci_error.js, test/citestutils.js
Fixed issue with events still being processed after a `callback(err)` for a fatal error that should have terminated the program.
The event driven nature of this library means that events may still be processed after receiving a fatal error event. Node.js version 10 seems to have particularly exposed this problem. The documentation of `removeAllListeners()` has been clarified in Node and it is made clear that this is not an appropriate function for the behaviour we need of preventing further event handling after a fatal error. The usage of `removeAllListeners()` has been removed.
* Added `addEventListener` function that wraps listeners in error flag checking to avoid emitting errors more than once and stop …
=> Fixed error handling issues exposed in Node 10

CHANGES.md, README.md, bin/couchbackup.bin.js, bin/couchrestore.bin.js, includes/parser.js, includes/request.js, package-lock.json
Corrected name of `iamTokenUrl` option
Changed name from `iamTokenEndpoint` to `iamTokenUrl`.
The `config.js` already asserts the correct name. The override is being tested as part of IAM acceptance testing.
N/A
=> Corrected name of iamTokenUrl option

CHANGES.md, package.json
- [FIXED] Concurrent database backups use the same default log file.
- [FIXED] IAM token URL override option.
=> Prepare for 2.3.1 release

.travis.yml
Changed Travis to use `npm install` for compatibility with `package-lock`.
Preemptively fixes the same [style of issue observed in `cloudant-follow`](https://github.com/cloudant-labs/cloudant-follow/issues/78) for greenkeeper branches
Travis uses `npm ci` by default, which does not update the `package-lock` file. Changed the `install` step to explicitly use `npm install`:
```yaml
install: npm install
```
- "No change"
- "No change"
- "No change"
=> Changed to npm install for travis

CHANGES.md, README.md, app.js, bin/couchbackup.bin.js, bin/couchrestore.bin.js, includes/config.js, includes/parser.js, includes/request.js, test/app.js, test/citestutils.js, test/config.js, test/parser.js, test/request.js
When running a backup it can take a very long time for the Cloudant server to respond to a `/_bulk_get` request (e.g. if it encounters a `500 Internal error`). There is no way to set a timeout without modifying the source code.
1. Have a CouchDB server that takes a very long time respond to a `/_bulk_get` request
1.1. We ran CouchDB at our Cloudant cluster smrt003 which yeilded `500 Internal errors` every now and then when using the default `couchbackup` option `opts.batchSize=500`
2. Run the example script `node ./examples/s3-backup-stream.js --source https://user:pass@example.com/my_database --bucket my_bucket --s3url s3.amazonaws.com --awsprofile default` with default `couchbackup` options.
Backup `/_bulk_get` requests in `./includes/backup.js` should happen in a timely manner. 
If …
=> Request timeout

package-lock.json, toxytests/toxy.js
The removal of the legacy URL APIs in #256 updated the `toxy.js` test file, but the `auth` property is not available on the new URL object leading to test failures.
Run the toxy tests with credentials.
Toxy tests to pass.
Toxy tests fail with `401`.
Corrected `toxy.auth` option to:
```js
auth: `${backendUrl.username}:${backendUrl.password}`
```
- "No change"
- Small change to passing of credentials for toxy tests.
- No change for user facing code.
- Modified existing toxy tests to correct usage of new URL object instead of legacy URL API.
- Temporarily disabled other tests to run only toxy tests on this branch. `Jenkinsfile` changes will not be merged.
- "No change"
=> Correct toxy test auth

CHANGES.md, app.js, examples/s3-backup-file.js, examples/s3-backup-stream.js, includes/cliutils.js, includes/parser.js, package-lock.json, test/app.js
Added validation for options not valid when using `shallow` mode.
Fixes #262 
Changed the way defaults are handled to allow for the invalid default values to be removed in the shallow case.
1. The API defaults were already applied _after_ the arg validation so logging warnings for invalid shallow mode options in that API case was straightforward as part of the validation.
1. For the CLI there were a few problems:
1. The help messages were ugly in some cases including two copies of the default or showing an `undefined` default.
* Removed all commander defaults, since we were applying them separately anyway. This fixes the help text and avoids the defaults being present in the `program` variable.
* Added an `undefined` check when creating default option help text.
1. The CLI defaults were …
=> 262 enhanced validation

CHANGES.md, package.json
- [NEW] Added request timeout option. Set via env var `COUCH_REQUEST_TIMEOUT`,
as CLI option `--request-timeout`, or programmatically via
`options.requestTimeout`.
- [IMPROVED] Replaced usages of Node.js legacy URL API. Note this changes some
URL validation error messages.
- [IMPROVED] Documentation, help text and log warnings for invalid options in
"shallow" mode.
- [UPGRADED] Moved nodejs-cloudant dependency to 4.x.x.
=> Proposed 2.4.0 release

Jenkinsfile
Removed `sudo` and global install for `npm-cli-login` module during publish step.
Using new Jenkins executor image to run publication step.
Publication without errors
`EACCES` errors are observed during publish:
https://cloudant-sdks-jenkins.swg-devops.com:8443/job/couchbackup/job/master/15/execution/node/103/log/
The `sudo` installation of the `npm-cli-login` package is creating `$HOME/.npm` with `root` as the owner, causing subsequent errors when not running as root.
The package does not need to be installed globally and can therefore be installed without using `sudo` by qualifying the path used for the subsequent commands.
- "No change"
- "No change"
- "No change"
=> Removed need to sudo for npm registry login

CHANGES.md, package-lock.json, package.json
- [FIXED] Preserve document revisions in shallow backup.
=> Prepare for release 2.4.2.

CHANGES.md, package-lock.json, package.json
- [UPGRADED] Upgraded @cloudant/cloudant dependency to version 4.2.2.
- [NOTE] Updated minimum supported engine to Node.js 8 “Carbon” LTS.
=> Prepare version 2.5.0 release.

CHANGES.md, package-lock.json, package.json
- [FIXED] Issue with incorrect handling of percent-encoded user info characters
via @cloudant/cloudant dependency.
- [UPGRADED] Upgraded @cloudant/cloudant dependency to minimum version 4.2.3
- [IMPROVED] Added documentation around encoding of characters in the user info
subcomponent of the URL.
=> Prepare 2.5.1 release

CHANGES.md, package-lock.json, package.json
- [FIXED] Issue with compatibility with Nano 8.2.0.
=> Prepare 2.5.2 release

.travis.yml, CHANGES.md, Jenkinsfile, README.md, includes/shallowbackup.js, package-lock.json, package.json, test/shallowbackup.js
Shallow mode was failing with Nano versions of 8.2.2 or newer.
Fixes #339 
* Update the `@cloudant/cloudant` dependency to 4.3.0 minimum.
* Update the minimum engine to `10`.
* Workaround nano check by using GET instead of POST
* See https://github.com/cloudant/couchbackup/issues/339#issuecomment-696032881 - Nano 8.2.2 introduced an invalid check that blocks our `POST _all_docs?startkey=... {}` requests from reaching the server
* Update to minimum support Node version in line with current LTS support.
- "No change"
- Modified existing tests
* Updated mocks to return for `GET` instead of `POST`
* Updated test axes for current supported LTS version 10, 12, current
- "No change"
=> 339 shallow mode

CHANGES.md, package-lock.json, package.json
- [UPGRADED] Upgraded `@cloudant/cloudant` dependency to version `4.3.0`.
- [NOTE] Updated minimum supported engine to Node.js 10 "dubnium" LTS.
=> Prepare 2.6.0 release

README.md
the bluemix endpoints have been deprecated, the default endpoint currently is `https://iam.cloud.ibm.com/identity/token`. See also the README of the cloudant library imported by couchbackup https://github.com/cloudant/nodejs-cloudant/blob/master/README.md
N/A
No change
No new tests because I only updated the documentation
No change"
=> Update IAM deprecated endpoint

app.js
- _I'm employed by IBM UK, and created this fix as part of my job - can/do I need to tick the DCO?_
Fixes #352
Looks like a typo - with an `async.queue`, paused state is given by property `q.paused` - https://caolan.github.io/async/v3/docs.html#queue
- "No change"
- "No change"
Validated in our consuming program - nodejs warning `MaxListenersExceededWarning` is no longer emitted.
No regression test added as I'm new to this project, and don't have the time right now.
- "No change"
=> detect paused queue correctly when writing to stream

Jenkinsfile, test/citestutils.js
Change the test server configuration and override the token server used by tests.
Run Jenkins tests with a custom IAM token server.
Tests to pass.
Test failures.
* Add `CLOUDANT_IAM_TOKEN_URL` environment variable to IAM test runs
* Add new env vars and cred IDs to `Jenkinsfile`
* Update `test/citestutils.js` to pass IAM token URL to API tests.
- "No change"
- "No change"
Test config changes only, no change to existing tests.
- "No change"
=> Update test server config

CHANGES.md, package-lock.json, package.json
- [FIXED] Async queue pause/resume behaviour to avoid exhausting listener handles.
- [UPGRADED] Upgraded `@cloudant/cloudant` dependency to version `4.4.0`.
=> Prepare 2.6.1 release

CHANGES.md, app.js, includes/backup.js, includes/error.js, includes/request.js, includes/shallowbackup.js, includes/spoolchanges.js, includes/writer.js, package-lock.json, package.json, test/ci_concurrent_backups.js, test/fatalerrors.js, test/hooks.js, test/request.js, test/shallowbackup.js, test/spoolchanges.js, test/writer.js
Replace `@cloudant/cloudant` with `@ibm-cloud/cloudant`
Fixes #357
* Replace `@cloudant/cloudant` package dependency with:
* `@ibm-cloud/cloudant`
* `tough-cookie` (for session cookie support)
* `retry-axios` (for retry support)
* Make `request` client return an object containing `service` client and `db` for database name.
* Update service requests to use new calls and models.
* Use promise responses and update response handling where needed.
* Fix broken termination error handling.
- No API changes.
- Minor changes in non-API:
-  retry timings
-  error messages - this is the biggest user facing change here. Error codes remain the same, but the request URL is no longer trivially available to form part of `couchbackup`'s error message.
- "No change"
- Modified existing tests because:
* …
=> 357 update cloudant client

CHANGES.md, package-lock.json, package.json
- [UPGRADED] Cloudant client dependency from `@cloudant/cloudant` to `@ibm-cloud/cloudant`.
=> Prepare 2.7.0 release

CHANGES.md, includes/request.js, test/request.js
Set the `user-agent` header to the correct value.
Fixes #380
Set the `user-agent` header in an interceptor to avoid the SDK overriding it with its own value.
- "No change"
- "No change"
- Added new tests to assert `user-agent` header is correct.
- Request header updated so easier to log/debug requests originating from couchbackup.
=> Add user-agent in interceptor

test/fatalerrors.js
Correct some intermittently failing tests.
Fixes #382
As per #382 in some of the fatal error tests parallelism is at play and we can't guarantee to call all the mocks before the process terminates. The solution proposed here is to make all but one of the mock requests optional in these tests to allow the nock assertions to pass if the process terminates (with the correct error) before the subsequent requests.
- "No change"
- "No change"
Test corrections as outlined above. It has been green 3 builds in a row in Jenkins (with 3 branches in each) and many many times locally. 🤞 
- "No change"
=> 382 intermittent error test

CHANGES.md, README.md, app.js, includes/error.js, test/fatalerrors.js
This change extends a preflight check in a database restore function to make sure that a target database is a new and empty. It does that by confirming that the target database has 0 actual or deleted docs.
The check adds a new error `DatabaseNotEmpty` with an exit code 13.
Fixes #376 
Function `proceedIfDbValid` got split in two version for backup and restore, where restore version was changed to check that number of docs and deleted docs in a target database is zero.
- "No change"
- "No change"
- Added new tests:
- should terminate on `notEmptyDBErr` when database is not empty
- should terminate on `notEmptyDBErr` when database is not new
- Modified existing restore tests to reflect changed validation approach
- "No change"
=> Extend preflight check in a database restore function

CHANGES.md, includes/spoolchanges.js, test/spoolchanges.js
Split changes spooling into multiple requests.
Fixes #408 
I believe this will also close #101 (as `last_seq` responses will now be handled in the loop) and #100 (since the built-in retries will now apply per batch request for changes and not only for a single request i.e. retries of any given request will be from that `last_seq` not the beginning of the feed). 
Apply a `limit` to changes requests and iterate with `since` and `last_seq`.
_Reviewer notes_: what is an appropriate `limit` to use? I've chosen 100k as a starting bid.
- No API change, underlying change in behaviour should be transparent to users.
- "No change"
- Added new tests to cover collection of changes over multiple requests:
- `should keep collecting changes` - to validate multiple requests are made
- `should keep …
=> Split changes spooling

CHANGES.md, README.md, package-lock.json, package.json
_Notes_:
* checking the README is part of the release process and I noticed an out-of-date Node.js version there, so this PR includes a correction for that
```
- [FIXED] Corrected `user-agent` header on requests.
- [FIXED] Restore of shallow backups created with versions <=2.4.2.
- [IMPROVED] Added quiet option to backup and restore to suppress batch messages.
- [IMPROVED] Added a preflight check for restore function to make sure that a target database is new and empty.
- [IMPROVED] Added handling for errors reading log file.
- [IMPROVED] Split changes spooling to improve reliability on databases with
millions of documents.
- [UPGRADED] `@ibm-cloud/cloudant`, `commander` and `debug` dependencies.
```
=> Prepare 2.8.0 release

.secrets.baseline, Jenkinsfile
Update Jenkinsfile to avoid groovy interpolation of creds
For PRs without an associated issue and/or test/build issues
Run the Jenkins build.
Complete without warnings.
Warnings about interpolation of creds.
Use the env vars directly instead of interpolating them into commands. This means moving some of the env setting into the `sh` step and performing some groovy switching there to keep the existing behaviours.
- "No change"
- Improved best-practice for creds handling in Jenkins
- N/A build or packaging only changes - existing tests running and passing.
- "No change"
=> Ternary expansion to sh env var name

test/spoolchanges.js
The 25M spool changes test is intermittently timing out in Jenkins executor environment.
For PRs without an associated issue and/or test/build issues
Run the test.
Test to pass.
Test sometimes times out.
Increase the test timeout from 2 to 5 minutes. It will still finish faster when it can, but this will avoid intermittent failures when the executor is not performing as fast as usual.
- "No change"
- "No change"
- Modified existing test to incease timeout.
- "No change"
=> Increase 25M spooling test timeout

.secrets.baseline, Jenkinsfile
Update Jenkinsfile to avoid groovy interpolation of `NPM_TOKEN`
For PRs without an associated issue and/or test/build issues
Run the Jenkins build
Complete without the following warning:
```
The following steps that have been detected may have insecure interpolation of sensitive variables (click here for an explanation):
sh: [NPM_TOKEN]
```
A warning about interpolation of `NPM_TOKEN`.
Use the `NPM_TOKEN` env var directly instead of interpolating it into the commands.
- "No change"
Improved best-practice for creds handling in Jenkins
* N/A build or packaging only changes - existing tests running and passing.
- "No change"
=> Fix NPM_TOKEN Groovy interpolation warning

CHANGES.md, package-lock.json, package.json
```
- [FIXED] Regression from version 2.7 resulting in incorrect handling of percent-encoded credentials in the URL user-info.
```
=> Prepare 2.8.1 release

CHANGES.md, package-lock.json, package.json
- [UPGRADED] `@ibm-cloud/cloudant` dependency to version `0.0.24`.
=> Prepare 2.8.2 release

CHANGES.md, package-lock.json, package.json
- [UPGRADED] `@ibm-cloud/cloudant` dependency to version `0.1.1`.
- [NOTE] Move `retry-axios` and `ibm-cloud-sdk-core` to peerDependencies.
=> Prepare 2.8.3 release

.secrets.baseline, Jenkinsfile, package-lock.json, package.json, test/hooks.js
This PR properly encodes password in Jenkins pipeline [as required by our own README](https://github.com/cloudant/couchbackup#the-url) and decodes it in test's hook, since node's `new URL` doesn't do that. This solves an issue with test password that might contain URL components.
Also this PR bumps `eslint` and `eslint-config-standard` to unlock its cross deps, that break `npm ci`
=> Properly urlescape password in tests hook and Jenkins pipeline

.travis.yml, CHANGES.md, Jenkinsfile, README.md, package-lock.json, package.json
Fixes #471 
Update minimum node engine requirement from 12 to 14 and Node.js versions in test matrix.
Update engine requirement to `"node": ">=14"`
Made the changes based on the previous node engine update: https://github.com/cloudant/couchbackup/pull/364
No change
No change
Test with Node.js supported LTS versions `14` and `16` and current version 18.
No change
=> Update Node engine to 14

CHANGES.md, package-lock.json, package.json
Prepare for 2.9.0 release
Changes:
```
- [UPGRADED] `@ibm-cloud/cloudant` dependency to version `0.1.2`.
- [NOTE] Updated minimum supported engine to Node.js 14 `fermium` LTS.
```
=> Proposed 2.9.0 release

CHANGES.md, package-lock.json, package.json
- [UPGRADED] `@ibm-cloud/cloudant` dependency to version `0.1.4`.
=> Prepare 2.9.1 release

CHANGES.md, package-lock.json, package.json
- [UPGRADED] `@ibm-cloud/cloudant` dependency to version `0.1.5`.
- [UPGRADED] `ibm-cloud-sdk-core` peerDependency to version `3.1.0`.
=> Proposed 2.9.2 release

Jenkinsfile
#495 didn't work as expected and the `BRANCH_IS_PRIMARY` check doesn't seem to work for scripted pipeline checkout of the new `main` default branch.
Revert to using a branch name check, but ofc use the new default branch name of `main`.
I tested the change on a replay of the last `main` build and the name check correctly produced a snapshot.
- "No change"
- "No change"
- "No change"
=> ci: check branch name for snapshot publish

CHANGES.md, package-lock.json, package.json
- [UPGRADED] `@ibm-cloud/cloudant` dependency to version `0.2.0`.
=> Prepare 2.9.3 release

Jenkinsfile, package-lock.json, package.json
Following up https://github.com/cloudant/couchbackup/pull/472
In ec53528 I renamed the path of `mocha` because of the breaking change:
* [#4863](https://github-redirect.dependabot.com/mochajs/mocha/issues/4863): Rename executable bin/mocha to bin/mocha.js
Bumps [mocha](https://github.com/mochajs/mocha) from 9.2.2 to 10.0.0.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/mochajs/mocha/releases">mocha's releases</a>.</em></p>
<blockquote>
<h2>v10.0.0</h2>
<h1>10.0.0 / 2022-05-01</h1>
<h2>:boom: Breaking Changes</h2>
<ul>
<li>
<p><a href="https://github-redirect.dependabot.com/mochajs/mocha/issues/4845">#4845</a>: <strong>Drop Node.js v12.x support</strong> (<a href="https://github.com/juergba"><strong><code>@​juergba</code></strong></a>)</p>
</li> …
=> Bump mocha from 9.2.2 to 10.0.0

CHANGES.md, package.json
Related to #510
Added `axios`<1.0.0 temporarily to the `peerDependencies` until https://github.com/axios/axios/issues/5000 is not resolved.
- "No change"
- "No change"
Unit tests passing after these steps:
```
rm package-lock.json
rm -rf node_modules
npm install <-- will install axios version 0.26.1 that does not have the bug
npm run unit
```
- "No change"
=> Add axios ^0.26.1 as a peer dependency

CHANGES.md, package-lock.json, package.json
- [UPGRADED] `@ibm-cloud/cloudant` dependency to version `0.2.1`.
- [NOTE] Add `axios` to peerDependencies.
=> Update version to 2.9.4

CHANGES.md, package-lock.json, package.json
- [UPGRADED]  `@ibm-cloud/cloudant` dependency to version `0.3.0`.
=> Proposed 2.9.5 release

CHANGES.md, includes/config.js
Replace `tmp.fileSync().name` in [apiDefaults](https://github.com/cloudant/couchbackup/blob/f44a8a3fe2967cd33e32dd911b699f019bbee1a4/includes/config.js#L27) with `tmp.tmpNameSync()` to discard descriptor of temporary file during backup.
fixes #535 
Update `tmp` call in `includes/config.js`
Used this [gist](https://gist.github.com/emlaver/9239ce5e12182e158b00739825a9e89b) to verify that file descriptors are discarded once backup completes.
=> fix file descriptor leak in backup

CHANGES.md, package-lock.json, package.json
- [FIXED] HTTP client dependency issue that masked backup errors when server connection was dropped.
- [FIXED] Discard temporary file descriptor for backup.
- [UPGRADED] `@ibm-cloud/cloudant` dependency to version `0.4.0`.
- [UPGRADED] `ibm-cloud-sdk-core` peerDependency to minimum version `4.0.2` to match version provided from `@ibm-cloud/cloudant`.
- [UPGRADED] `axios` peerDependency to minimum version `1.2.1` to match version provided from `ibm-cloud-sdk-core`.
=> Prepare 2.9.6 release

package.json
Pinned versions are used from the package-lock.json file. Dependabot will notify us when newer versions are available.
=> chore: pin dependency versions

CHANGES.md, package-lock.json, package.json
```
- [UPGRADED] `@ibm-cloud/cloudant` dependency to version `0.5.2`.
- [UPGRADED] `ibm-cloud-sdk-core` peerDependency to minimum version `4.0.8` to match version provided from `@ibm-cloud/cloudant`.
- [UPGRADED] `axios` peerDependency to minimum version `1.4.0` to match version provided from `ibm-cloud-sdk-core`.
- [NOTE] Repository moved from https://github.com/cloudant/couchbackup to https://github.com/IBM/couchbackup.
- [NOTE] Updated Node.js version requirement statement for LTS 16 and 18.
```
=> Prepare 2.9.10 release

CHANGES.md, package-lock.json, package.json
- [UPGRADED] `@ibm-cloud/cloudant` dependency to version `0.5.4`.
- [UPGRADED] `ibm-cloud-sdk-core` peerDependency to minimum version `4.0.9` to match version provided from `@ibm-cloud/cloudant`.
=> Prepare 2.9.11 release

.secrets.baseline, CHANGES.md, package-lock.json, package.json
- [UPGRADED] `@ibm-cloud/cloudant` dependency to version `0.6.0`.
=> Prepare 2.9.12 release

package-lock.json, package.json
Update peer dependency for `ibm-cloud-sdk-core` to `4.1.2`.
Using `ibm-cloud-sdk-core` `4.1.1` causes failures.
Tests to pass.
Tests fail - see https://github.com/IBM/couchbackup/pull/616 that included that core `4.1.1` with `@ibm-cloud/cloudant` `0.7.0` .
Raise the minimum peer dependency level to avoid using the broken version.
- "No change"
- "No change"
- "No change"
=> build(peer-deps): update ibm-cloud-sdk-core to 4.1.2

CHANGES.md, package-lock.json, package.json
- [UPGRADED] `@ibm-cloud/cloudant` dependency to version `0.7.1`.
- [UPGRADED] `ibm-cloud-sdk-core` peerDependency to minimum version `4.1.2` to match version provided from `@ibm-cloud/cloudant`.
- [NOTE] Updated minimum supported engine to Node.js 18 `hydrogen` LTS.
=> Prepare 2.9.13 release

test/ci_event.js, test/citestutils.js, test/test_process.js
Cleanups of the last failing tests after #621 and #623.
Part of i272.
* Add backup promises for the callback and finished events and "all" them.
* Special cased the stdout test so it isn't part of a pipeline, otherwise it gets closed out and mocha can't write anything else to it.
* Cleaned up the event tests with promises.
Note should merge after #623 with just 7cd4c48139191627e27b02ec1ff91781ccc75f62 and bd26397f27632575336dd9643b3bc670a7f27624
- "No change"
- "No change"
- Modified existing tests as outlined above.
- Introduced a new paramter for using stdout.
- Added some extra logging in clitestutils.
=> Modernize test backup/restore - cleanups

.secrets.baseline, Jenkinsfile
Prepare the for default agent to move to Node 20 by explicitly asking for Node 18.
Add `container('node18')` wrapping for most stages.
Remove `container('node20')` for the (currently unused) Node 20 stage.
- "No change"
- "No change"
- "No change"
=> ci: use node18 container

.secrets.baseline, Jenkinsfile
Avoid groovy interpolation by using Node's encodeURIComponent in a shell evaluation.
Use a sub-shell to rn `node -e` of a js statement that calls `encodeURIComponent` of the environment variable and outputs the encoded value when evaluating the `COUCH_BACKEND_URL`  env var.
- "No change"
- Avoids Jenkins needing to do a groovy string interpolation of credentials.
- "No change"
=> test: avoid interpolation with node encoder

CHANGES.md, app.js, bin/couchbackup.bin.js, bin/couchrestore.bin.js, includes/cliutils.js, includes/error.js, test/app.js
fix: wrap ERR_INVALID_URL in InvalidOption
Fixes #635
* Export new`wrapPossibleInvalidUrlError` from `error` module
* function that checks for `ERR_INVALID_URL` and wraps it in `InvalidOption` type `BackupError`.
* To ensure that both places that construct a URL return the correct error type call `wrapPossibleInvalidUrlError` from
* app.js
* `cliutils.databaseUrl` 
* To ensure that the CLI process exits with the correct code add `try`/`catch` blocks to `couchbackup.bin.js` and `couchrestore.bin.js` that call the `error.terminationCallback` instead of an unhandled error if an error occurs before we are in the backup or restore functions.
- "No change"
- "No change"
- Modified existing tests because to remove `TypeError` from test assertions as it should have the correct `InvalidOption` …
=> fix: wrap ERR_INVALID_URL in InvalidOption

includes/liner.js, includes/logfilegetbatches.js, includes/logfilesummary.js, includes/restore.js, includes/spoolchanges.js, test/writer.js
Replace custom liner with built-in readline.
Part of i251
* Make a new `Liner` class that uses the built-in `node:readline` module.
* Extend a `Transform` stream to wrap the `readline` `createInterface`.
* Replace usages of `liner` with `Liner`.
- "No change"
- "No change"
- Modified existing tests that use `liner` to use `Liner`
- No other new tests because the liner code is exercised by existing tests.
- "No change"
=> refactor: replace liner with built-in readline

.secrets.baseline, test/fatalerrors.js
Improve error handling in fatal errors suite.
Fixes #640 
* Make `testPromiseWithAssertNock` and use it from all tests so the nock assertion can be controlled in one place.
* Move the `assertNock` from `then` to `finally` so that in cases where the test failed with an error we can see if nock was complete.
* Add an `error` event listener for the CLI test proxy and write a `400` result when errors are encountered. This prevents the proxy server blocking subsequent requests.
* Add a `no match` event listener for `nock` in the test `before` (and remove it in the `after`). This way any unmatched requests can be logged which makes debugging easier.
- "No change"
- "No change"
- Modified existing tests as outlined above to fix #640.
- "No change"
=> test: improve error handling in fatal errors suite

includes/transforms.js, test/transforms.js
Add pipeline transform duplex streams.
Fixes i250 i253 i254 i255
* Add `transforms.js` with a series of transforming duplex streams
* Add a BatchingStream for batching elements into arrays
* Add a SplittingStream for flat-mapping a batch back to elements
* Add a MappingStream for mapping stream elements to something else
- "No change"
- "No change"
- Added new unit tests for each transform stream type
- "Added new logging group `couchbackup:transform` with subgroup `batch` for debug of the batching implementation.
=> refactor: add pipeline transform duplex streams

CHANGES.md, package-lock.json, package.json
- [FIXED] Corrected error handling for invalid URLs.
- [UPGRADED] `@ibm-cloud/cloudant` dependency to version `0.7.2`.
- [UPGRADED] `ibm-cloud-sdk-core` peerDependency to minimum version `4.1.4` to match version provided from `@ibm-cloud/cloudant`.
- [UPGRADED] `axios` peerDependency to minimum version `1.6.0` to match version provided from `ibm-cloud-sdk-core`.
=> Prepare 2.9.14 release

includes/backupMappings.js, test/backupMappings.js
Add backup mapping functions for use in future pipeline.
Fixes i258
Created 5 mapping functions (and some unexported helper functions).
Some of the code is copied from existing `backup.js` and `logfile*.js` - the code in those files is still active until we start using these mapping functions in pipeline transforms later on.
The inputs and outputs are:
file lines (either log or backup)
backup batch objects of the form `{command: t|d|changes_complete, batch: #, docs: []}`
The mapping functions are:
| function | input | output | purpose |
| --- | --- | --- | --- |
| backupBatchToBackupFileLine | `{command: 'd', batch: #, docs: [full docs]}` | stringified docs | wiriting backup file |
| backupBatchToLogFileLine | `{command: 'd', batch: #, docs: []}` | `:d batch#` log file line | writing log …
=> refactor: add backup mapping functions

includes/transforms.js, test/transforms.js
Add `PassThrough` stream that performs side effects
Fixes i252
- Add new `SideEffect` class that accepts a custom function
- Non-async functions are handled in `async doSideEffect`
Added tests to assert side effect by passing in sync and async functions.
=> Add PassThrough stream that performs side effects

.secrets.baseline, test/fatalerrors.js
Run the fatal error tests repeatedly on a busy system.
All tests to pass.
The test intermittently fail (particularly the CLI restore tests).
These tests fork a new Node process and also make real requests against mocks (via a proxy).
This amount of work seems to sometimes trigger the default 2s test timeout on busy systems.
Inrease the test timeout for these tests to 10 s.
- "No change"
- "No change"
- Modified existing tests as outlined above. I tested 15 builds with the increased timeout and did not see any failures, previously the timeout failure would occur approximately 1 in 5.
- "No change"
=> test: intermittent failures in fatal error tests

includes/backupMappings.js, includes/transforms.js, test/backupMappings.js, test/fixtures/test2.log, test/transforms.js
Modifications to the work delivered in #652 to bring it more in line with what was done in #658.
Fixes part of i258
* Move the mapping functions into two classes `LogMapper` and `Backup`.
* Use the `Liner` object format with line numbers in the mapping functions.
* Make the `pendingToFetched` use the same `await`/`try`/`catch` style as `pendingToRestored`.
* Add a new `FilterStream` (missed from #654).
* Add end to end testing of the mapping.
- "No change"
- "No change"
- Added new tests:
- `FilterStream` testing
- `end to end mapping` test using a pipeline
- Modified existing backup mapping tests to use the Liner object format delivered in #658.
- Minor tweaks to debug loginng.
=> refactor: backup mappings

includes/spoolchanges.js, includes/transforms.js, test/transforms.js
Add `Writable` instances that delegate to another `Writable`.
Fixes i259
* Re-ordered transforms and renamed test describe blocks
* Added 2 new classes:
* `DelegateWritable` - a `Writable` implementation that simply delegates to another `Writable`. Special handling is added for `process.stdout`. It is not "endable" while the process is running so we need to detect that case to use it at the end of a pipeline.
* `WritablePassThrough` - a special case of the `SideEffect` pass through that uses a `DelegateWritable` for performing side effects. This allows for the case of writing a log file from a middle stage of a pipeline.
* Updated `spoolchanges` to use the `DelegateWritable` as much of the functionality was similar to the `LogWriter` there.
- "No change"
- "No change"
- Added new tests in …
=> refactor: writable wrappers

Jenkinsfile, README.md, package-lock.json, package.json
Add Node version 20 to README and package.json.
Update existing build/test stages and add Node 18 and Node 21 test stages.
- Add Node 20 to engine in `package.json` and lock file
- Add Node 20 to README
- Update existing Jenkins test stages to use Node 20
- Add new stage for Node 18x and current Node 21x
=> Update Node version info

app.js, includes/error.js
This is an async rewrite of pre-flight checks for backup and restore functions to do a pre-work to conversion from internal event emitter + callbacks to streams rewrite.
The steps done: 
- Simplify and DRY `validateArgs` in `app.js`
- Convert all validation functions to `async`, convert backup/restore to use them in promise chain fashion.
=> refactor: Promisify backup and restore pre-flight checks

.secrets.baseline, app.js, includes/backup.js, includes/error.js, includes/logfilegetbatches.js, includes/logfilesummary.js, includes/spoolchanges.js, test/ci_error.js, test/fatalerrors.js, test/logfilegetbatches.js, test/logfilesummary.js, test/spoolchanges.js
Migrate the full backup functionality to a streams pipeline.
Fixes i264 and i265.
* refactor: resume log file handling
* Replace JS object with `Map` for storing state
* `logFileSummary` replaced with a pipeline that reads log file metadata only and resolves with a summary of pending batch numbers
* `logFileGetBatches` returns an array of streams that can be composed into a pipeline that maps log file data to pending backup batches
* refactor: spoolchanges for backup pipeline & fix: spool changes uses non-existent error name
* changed to return an array of streams that can be composed into a pipeline that streams changes and adds pending batches to a log file
* fix a bug where an invalid change used an error name not present in `errors.js`
* make `LogWriter` a `WritableWithPassThrough` so …
=> refactor: backup pipeline

app.js, includes/backup.js, includes/backupMappings.js, includes/request.js, includes/restore.js, includes/restoreMappings.js, includes/shallowbackup.js, includes/spoolchanges.js, test/backupMappings.js, test/citestutils.js, test/request.js, test/restore.js, test/restoreMappings.js, test/shallowbackup.js, test/spoolchanges.js
Update the request class.
Fixes i313
* Remove obsolete code for handling streams that is no longer needed.
* Fix some lint errors for object shorthand.
* Renames as proposed in https://github.com/IBM/couchbackup/pull/669#discussion_r1424275938
* function `client` -> `newClient`
* returned client object `db` -> `dbName`
* usages of the object renamed from `db` to `dbClient`
- Internal renames.
- "No change"
- Modified existing tests to match new names.
- Added debugging in interceptor.
=> reafctor: request class cleanup and renames

app.js, includes/backup.js, includes/backupMappings.js, includes/error.js, includes/restoreMappings.js, includes/shallowbackup.js, test/request.js, test/restore.js, test/restoreMappings.js, test/spoolchanges.js
Simplify error handling.
Fixes i269
* Rename `convertResponseError` to `convertError`
* Combine error conversion functionality in single function
* Move conversion calls to `app.js` at end of pipeline
- "No change"
- "No change"
- Modified existing tests because in places the test code needs to call `convertError` to make the assertions easier.
- "No change"
=> refactor: common error handling

app.js, includes/backup.js, includes/restore.js, includes/restoreMappings.js, includes/transforms.js, test/restore.js, test/restoreMappings.js
Tidy up the even emitters after the pipeline refactoring.
Fixes i268
* Move `finished` events to fire alongside the `callback` at the end of the app.js promise chain.
* Pass the event emitter to backup/restore for the interim events to be emitted (`changes`/`written` and `restored` respectively)
* Keep the running totals in the internal backup/restore functions and return them as the resolved promise value.
* Don't track the total in individual restore batch "chunks" because they can get out of order.
- Internal changes only.
- "No change"
- Modified existing tests because ...
- "No change"
=> refactor: event emitters

includes/allDocsGenerator.js, test/allDocsGenerator.js
Implement `_all_docs` async generator to be used by shallow backup pipeline in issue 267.
Fixes i271
- Implement async generator that yields docs within the `_all_docs` result
- Add some debugging statements
- "No change"
- "No change"
- Add new tests for asserting: 
- all documents passed through pipeline are expected compared to original test fixture files 
- "No change"
=> refactor: add async all docs generator

includes/liner.js, includes/logfilegetbatches.js, includes/logfilesummary.js, includes/restore.js, test/backupMappings.js, test/liner.js, test/restoreMappings.js
refactor: remove liner constructor arg
Fixes part of i312
All the places using `Liner` are now expecting the `{lineNumber: #, line: content}` form and not raw lines so we can remove the constructor arg.
- I"No change"
- "No change"
- Added a new test for checking the lineNumber output on each line.
- Modified existing tests that no longer need to specify the boolean.
- "No change"
=> refactor: remove liner constructor arg

includes/config.js, package-lock.json, package.json
refactor: use built-in mkdtemp to create a unique log file and remove `tmp` dependency
Fixes i311
* Tidy up imports and object shorthand in `config.js`
* Replace generated log file name: `tmp.tmpNameSync()` with a timestamp file name in a new temp directory with a random suffix in the OS tmp dir. The random suffix of `mkdtemp` should provide suffiicient uniqueness, but if it doesn't the timestamp provides additional variability.
* Remove the `tmp` dependency.
Note that #535/#536 dealt with an error in this area before. The built-in [`mkdtemp`](https://nodejs.org/docs/latest-v18.x/api/fs.html#fsmkdtempprefix-options-callback) returns a directory name, not a fd. So although this change creates the dir it preserves the previously fixed behaviour of having only a name in this part of the code …
=> refactor: use built-in mkdtemp

includes/spoolchanges.js
fix: use bufferSize for seqInterval
Fixes part of i312
Adjust the `seqInterval` to match the `bufferSize` - this should mean we get at least one seq ID per batch we backup (unless the database is very small i.e. smaller than one batch).
- "No change"
- "No change"
- No new tests because code path is covered by existing tests, changing the seqInterval does not impact any other behaviors at present.
- `:changes_complete` log entries are more likely to have a sequence ID.
=> fix: use bufferSize for seqInterval

.secrets.baseline, app.js, includes/error.js, test/app.js, test/citestutils.js
Add some additional options validation for the `resume` cases.
Fixes part of i312.
* Add new `LogFileExists` error (code 23).
* Rework `validateLogOnResume` function to split into 3 parts (no options, resuming and not resuming) with additional checks in the latter 2 parts relating to the log file.
* Add a bufferSize warning line to `validateLogOnResume`.
- Backup error thrown if a specified log file exists and it is a new backup.
- "No change"
- Added new tests:
- assert the buffer size warning is printed when using `resume` and `bufferSize` options.
- assert the `LogFileExists` error is thrown when not using `resume` and specifying an existing log file.
- Modifed existing tests to avoid creating a log file in advance of the backup because that is now an error condition. Instead we have a …
=> fix: additional resume options validation

includes/backup.js
A tiny cleanup change to make it clear what `time` in backup emitter's "written" object means.
=> refactor: explicitly name running time var

.secrets.baseline, Jenkinsfile
The fatal error unit tests failed right before the merge of https://github.com/IBM/couchbackup/pull/662.
This most likely happened when our kube CI resources were strained and being throttled .  Increasing the CPU request to 1 and disabling concurrent builds should hopefully allow for enough resources so that the test suite doesn't time out.
fixes i316
=> ci: increase CPU request to 1 and disable concurrent builds

bin/couchrestore.bin.js, includes/restore.js
Match restore output to what is produced by backup.
Backup tracks the total time taken for a backup and emits it as part of the `written` progress event emitted after each batch.
Restore did not have equivalent functionality, but it is quite useful for making quick checks on performance impact of the `modernization` changes.
The output from the `restored` event  was also only the total number of revisions, but did not indicate the batch ID like backup does.
The change adds the time taken to the emitted `restored` event and changes the CLI output format for `couchrestore` to match that for backup e.g.
` couchbackup:restore:batch Restored batch ID: 0 Total document revisions restored: 1 Time: 0.029`
- Non-breaking change, adds `time` property to `restored` event object.
- "No change"
- No …
=> feat: add time to restore output

includes/restore.js, includes/transforms.js, test/transforms.js
* Fix batching back-pressure
* Replace `SplittingStream`->`BatchingStream` with new `BatchingStream` with re-batching.
* Reduce double-buffering on mapping streams.
Part of i330.
* `fix: batching Duplex with back-pressure`
* Re-implement the `BatchingStream` as a `Duplex` instead of a `Transform` to allow finer control over read/write back-pressure.
* Add `rebatch` flag to `BatchingStream` that switches from accepting single elements to accepting arrays and spread the arrays when pushing available elements.
* See code comments for full details.
* `fix: minimize buffering on map passthroughs`
* The `DuplexPassThrough` used in the mapping transforms would default to a buffer size of 16 objects, this could be very large batches. In practice there is no need for this stream to buffer at all …
=> fix: large test regressions for back-pressure and memory footprint

test/spoolchanges.js
test: match follower batch size in spoolchanges
Fixes i333
Adjust the mock changes response number of changes to match the batch size used by the follower (10k).
Using larger batches made the tests perform poorly and was not representative of real operation.
- "No change"
- "No change"
- Modified existing tests to stop them timing out by using smaller batch sizes. Also improved the test comments to make the difference between the 2 batch sizes more clear.
- "No change"
=> test: match follower batch size in spoolchanges

.secrets.baseline, examples/README.md, examples/package.json, examples/s3-backup-file.js, examples/s3-backup-stream.js
Clean up the S3 example scripts.
Fixes #694 
* Extende the `examples/README.md` with additional instructions and details.
* Clean up dependencies
* Add dependency on latest `2.x` `@cloudant/couchbackup` (docs said it was using the repo version, but the code had been changed when the package became scoped that it wasn't actually using the checked out version - better to just use latest compatibile shipped version).
* Use latest modular v3 `aws-sdk` for `client-s3`, `credential-providers`, `lib-storage`
* Remove dependency on `tmp`
* Remove unusued `dev-dependencies`
* Clean up `package.json` to update version to `0.0.2` and remove unused script command.
* Update script code for latest `aws-sdk` changes.
* Add `couchbackup` event handlers for additional progress/debug.
- "No change"
- "No …
=> docs: clean up s3 examples

test/ci_error.js
Destory unused stream to avoid deprecated GC file cleanup.
Fixes: i338
The write error tests use a read stream as a backup destination to test errors of that type. As such the read stream created by the test is never read to the end and thus not automatically cleaned up. The GC file cleanup happens eventually, but produces a deprecation warning and will in future cause tests to error.
To avoid this we call `destroy` on the stream in the test `finally`.
- "No change"
- "No change"
- Modified existing tests as described above.
- "No change"
=> test: destroy unused stream

package-lock.json, package.json, test/compare.js
Do the post test database comparions batch wise to reduce overhead.
Fixes part of i320
The database comparison obtained a full list of document IDs from 2 databases (that should be identical) and proceeded to identify all the missing revisions. For large databases the full ID list being in memory (twice) plus a third copy for the union consumes a significant amount of memory.
Whilst it is potentially useful to know the complete list of missing IDs/revs from an automated test perspective it is preferable for us to "fail fast" instead.
This PR reworks the comparison to a fail fast approach by doing these checks:
* Introduce `getDatabaseInfo` checks upfront and compare the number of docs and deleted docs (if they don't match the databases don't match and we can bail quickly)
* Since when we …
=> test: do dbcompare batch wise to reduce overhead

package.json
Package only necessary content.
Fixes part of i303
Add `files` property to `package.json`
- "No change"
- "No change"
- N/A build or packaging only changes, ran `npm publish --dry-run`
```
npm notice 
npm notice 📦  @cloudant/couchbackup@2.9.17-SNAPSHOT
npm notice === Tarball Contents === 
npm notice 11.3kB LICENSE                      
npm notice 16.2kB README.md                    
npm notice 16.5kB app.js                       
npm notice 2.7kB  bin/couchbackup.bin.js       
npm notice 2.1kB  bin/couchrestore.bin.js      
npm notice 9.3kB  includes/backup.js           
npm notice 1.3kB  includes/change.js           
npm notice 1.8kB  includes/cliutils.js         
npm notice 3.4kB  includes/config.js           
npm notice 3.0kB  includes/error.js            
npm notice 1.4kB …
```
=> build: package only necessary content

CHANGES.md, package-lock.json, package.json
- [IMPROVED] Examples and related documentation.
- [IMPROVED] Reduced package size.
- [UPGRADED] `@ibm-cloud/cloudant` dependency to version `0.8.3`.
- [UPGRADED] `commander` dependency to version `12.0.0`
- [UPGRADED] Examples to use latest dependencies.
=> Prepare 2.9.17 release

CHANGES.md, package-lock.json, package.json
- [NEW] Included `time` in `restored` API events and CLI output.
- [NEW] Added metadata to backup files.
- [FIXED] Double output of errors to stderr when using CLI.
- [FIXED] Error for broken JSON in backup files.
- [FIXED] Wrong error code used for incomplete changes item.
- [FIXED] Error if the log file already exists when starting a new backup.
- [REMOVED] Dependency on `async` module.
- [REMOVED] Dependency on `tmp` module.
- [REMOVED] Unused request handling code.
- [IMPROVED] Increased tolerance to server and network errors when spooling changes (via cloudant-node-sdk changes follower).
- [IMPROVED] Avoided double parsing of JSON batches when resuming a backup.
- [IMPROVED] Resumed backups identification of incomplete backup lines during restore.
- [IMPROVED] Added line numbers to …
=> Prepare 2.10.0 release

CHANGES.md, package-lock.json, package.json
- [IMPROVED] Updated documentation.
- [UPGRADED] `@ibm-cloud/cloudant` dependency to version `0.9.1`.
=> Prepare 2.10.1 release

Jenkinsfile, test-network/conditions.js
This PR switches back on unreliable network tests with use of toxiproxy.
The original tests been:
| test | conditions | comment | 
| --- | --- | --- | 
| normal | No poisons to add | |
| bandwidth-limit | `poison(tpoisons.bandwidth({ bytes: 512, threshold: 1 }));` | 0.5 MB/s |
| latency | `poison(tpoisons.latency({ max: 1500, min: 250 })).withRule(trules.probability(60))` | |
| slow-read | `poison(tpoisons.slowRead({ chunk: 256, threshold: 1 })).withRule(trules.timeThreshold({ duration: 1, period: 100 }))` | Slow read for 10 % of the time e.g. 1 ms in every 100 | 
| rate-limit | `'/*/_bulk_get' poison(tpoisons.rateLimit({ limit: 20, threshold: 1000 }))` + `'/*/_bulk_docs' poison(tpoisons.rateLimit({ limit: 10, threshold: 1000 }))` | Simulate the Cloudant free plan with 20 lookups ps and …
=> Add unreliable network tests with toxiproxy

CHANGES.md, package-lock.json, package.json
- [UPGRADED] `@ibm-cloud/cloudant` dependency to version `0.10.1`.
- [UPGRADED] `ibm-cloud-sdk-core` peerDependency to minimum version `5.0.1` to match version provided from `@ibm-cloud/cloudant`.
- [UPGRADED] `axios` peerDependency to minimum version `1.7.4` to match version provided from `ibm-cloud-sdk-core`.
- [UPGRADED] `commander` dependency to version `12.1.0`
- [UPGRADED] `debug` dependency to version `4.3.6`.
=> Prepare 2.10.2 release

CHANGES.md, package-lock.json, package.json
- [NEW] *EXPERIMENTAL/UNSUPPORTED* Add `attachments` option to backup and restore attachments for Apache CouchDB.
- [UPGRADED] `@ibm-cloud/cloudant` dependency to version `0.10.3`.
- [UPGRADED] `ibm-cloud-sdk-core` peerDependency to minimum version `5.0.2` to match version provided from `@ibm-cloud/cloudant`.
- [UPGRADED] `debug` dependency to version `4.3.7`.
- [NOTE] The `attachments` option is not supported. Do not use for IBM Cloudant backups.
=> Prepare 2.11.0 release

CHANGES.md, includes/request.js, package-lock.json, package.json
Fix interceptor ordering issue and tidy up.
Fixes i414
* Enable retries  _after_ all other interceptors are registered
* Replace custom retry configuration with SDK's `enableRetries` and remove related peerDependency.
* Use named functions for interceptors and ensure user-agent is set on token requests also.
- "No change"
- "No change"
Retries are covered by existing tests.
- "No change"
=> fix: interceptor ordering with retries

Jenkinsfile, package-lock.json, package.json
#788 plus switch from incompatible `mocha-jenkins-reporter` to mocha's built-in `xunit` reporter.
* Remove `Jenkinsfile` install of `mocha-jenkins-reporter` plugin
* Adjust mocha reporter options to use `xunit`
- "No change"
- "No change"
- Modified reporting of existing tests. Output differences can be compared between this branch and `main`. Test numbers are identical, the only difference is the `(root)` test root here, vs `test` and `test-iam` previously. The tests are still grouped by files though, as visible in blue ocean so there should be no issue seeing which branches have failures.
- "No change"
=> ci: Mocha xunit reporter

CHANGES.md, package-lock.json, package.json
- [UPGRADED] `@ibm-cloud/cloudant` dependency to version `0.12.0`.
- [UPGRADED] `commander` dependency to version `13.0.0`
- [UPGRADED] `debug` dependency to version `4.4.0`.
=> Prepare 2.11.2 release

.secrets.baseline, CHANGES.md, includes/request.js, test/cliutils.js, test/request.js
Fixed encoding of special characers in database names.
Fixes #801
The command line database name parameter is encoded into a URL (for historical API compatibility reasons) and then extracted again for use with the client HTTP calls.
The client automatically encodes the db parameter before using it in a URL so to avoid double-encoding we need to decode it first.
- "No change"
- "No change"
- Added new tests:
- `test/cliutils.js` `#unit Check URL handling` `should encode database names` - to validate the encoding of the CLI parameter into the internal URL
- `test.request.js` `#unit Check database names` `should handle special characters` - to check that the db name is decoded for the client config object and re-encded by the client during a request
- "No change"
=> fix: avoid double encoding specials in db names

CHANGES.md, package-lock.json, package.json
- [FIXED] Encoding of special characters in database names.
- [UPGRADED] `commander` dependency to version `13.1.0`
=> Prepare 2.11.3 release

test/citestutils.js, test/test_process.js
Avoid encyrption key derivation warning in test code.
Run the encryption tests.
No warnings in logs.
```
[2025-01-27T13:48:42.014Z] *** WARNING : deprecated key derivation used.
[2025-01-27T13:48:42.014Z] Using -iter or -pbkdf2 would be better.
```
Change the options used on the `openssl` process to avoid the warning.
Also base64 encode the output and adjust the assertion to match.
- "No change"
- "No change"
- Modified existing tests because to avoid emitting warning and assert on base64 output.
- "No change"
=> test: avoid encryption key derivation warning

Jenkinsfile
Update Node version matrix in CI.
Fixes part of i399.
* Rename containers to match new names provided by kube agent template.
* Mock server port offset by constant, not version number.
- "No change"
- "No change"
- N/A build or packaging only changes - note build will fail until new template is merged.
- "No change"
=> ci: rename node versions

CHANGES.md, package-lock.json, package.json
- [UPGRADED] `@ibm-cloud/cloudant` dependency to version `0.12.1`.
=> Prepare 2.11.4 release

CHANGES.md, package-lock.json, package.json
- [UPGRADED] `@ibm-cloud/cloudant` dependency to version `0.12.2`.
- [UPGRADED] `ibm-cloud-sdk-core` peerDependency to minimum version `5.3.2` to match version provided from `@ibm-cloud/cloudant`.
- [UPGRADED] `axios` peerDependency to minimum version `1.8.2` to match version provided from `ibm-cloud-sdk-core`.
=> Prepare 2.11.5 release

CHANGES.md, README.md, package-lock.json, package.json
Remove EOL Node.js `18` from supported versions.
Fixes part of i458
* Update `README.md` to list Node.js `20` as the minimum supported version.
* Update `package.json` `engine` list to include Node.js LTS versions `20` and `22` (note that `24` will be production ready LTS in October)
* Add a note to `CHANGES.md` for next release.
- "No change"
- "No change"
- Test matrix versions are updated separately to remove Node.js 18.
- "No change"
=> Remove Node.js version `18` support

CHANGES.md, package-lock.json, package.json
- [IMPROVED] Avoid poll delay collecting changes from empty databases.
- [UPGRADED] `@ibm-cloud/cloudant` dependency to version `0.12.3`.
- [NOTE] Updated minimum supported engine to Node.js 20 LTS.
=> Prepare 2.11.6 release

test/transforms.js
JavaScript provides built-in methods to sort arrays, making it convenient for developers to manipulate data. There are two primary ways to sort an array:
`Array.prototype.sort()`: This method sorts the elements of an array in place and returns the sorted array.
`Array.prototype.toSorted()`: This method is designed to return a new sorted array, leaving the original array unchanged.
The default sort order is lexicographic (dictionary) order, based on the string representation of the elements. This means that when sorting an array of strings, numbers, or other elements, they are converted to strings and sorted according to their Unicode code points (UTF-16). For most cases, this default behavior is suitable when sorting an array of strings.
However, it’s essential to be aware of potential …
=> fix: sorting as SQ suggests

CHANGES.md, package-lock.json, package.json
- [UPGRADED] `@ibm-cloud/cloudant` dependency to version `0.12.6`.
- [NOTE] Add AI code policy to contributing guide.
=> Proposed 2.11.8 release

CHANGES.md, package-lock.json, package.json
- [UPGRADED] `@ibm-cloud/cloudant` dependency to version `0.12.7`.
=> Proposed 2.11.9 release

CHANGES.md, package-lock.json, package.json
- [UPGRADED] `@ibm-cloud/cloudant` dependency to version `0.12.8`.
=> Prepare 2.11.10 release
