examples/README.md, examples/package.json, examples/s3-backup-file.js, examples/s3-backup-stream.js
Fixes the minor bugs in the scripts in `examples`.
Fixes #98
=> Fix install and running of example scripts

CHANGES.md, README.md
I forgot to update docs & CHANGES in PRs gone by.
=> Smithsz patch 1

Jenkinsfile, README.md, examples/s3-backup-file.js, examples/s3-backup-stream.js
Automatically publish the library.
Added publishing stage to `Jenkinsfile`.
Will publish all `master` branch builds. If the `package.json` version is a SNAPSHOT then the `--tag snapshot` arg and a build identifier will be added otherwise it will publish as `latest` (the default) using the version number from the `package.json`.
Added automatic git tagging for release (i.e. non-snapshot) versions.
No new tests, build system changes.
Tested by using the `publishing` branch name instead of `master`. Can't be merged to master until there are some valid npm creds in Jenkins, but otherwise things appeared to work well.
=> Publishing

package.json
=> Fix package name to include the @cloudant scope

CHANGES.md, bin/couchbackup.bin.js
=> Run backup on file open

package.json
Fixed up some minor issues in the package.json.
Corrected whitespace.
Fixed lower bound of engine version.
No new testing, metadata change.
=> Fixed up package.json

Jenkinsfile, citest/citestutils.js, citest/test.js
Improved test reporting, increased timeouts and tried again to fix intermittent issue with compression tests.
* Changed test child processes to use `close` instead of `exit` event so that stdio streams are also closed before trying to assert the gz file. Hopefully this will finally resolve the intermittent failure in the compression tests.
* Updated to use mocha-jenkins-reporter instead of mocha-junit-reporter so that we can get both console and xml output and more clear test breakdowns in Jenkins.
* Increased timeouts so that some backup tests won't timeout when the test cluster is busy.
Test and build changes, no new tests.
=> Test improvements

CHANGES.md, includes/backup.js, includes/error.js
Verify database supports `/_bulk_get` endpoint prior to running backup.
Query `GET /_bulk_get`:
- 404 => endpoint is _not_ supported
- 405  => endpoint is supported
No additional tests added.
See #107.
=> Verify /_bulk_get endpoint is supported

test/ci_largee2e.js
Reduced to a single large end to end test.
Test change to avoid over-working CI system.
=> Reduced the large end to end tests

test/citestutils.js, test/request.js, toxytests/toxy.js
Added tests for rate-limit scenarios
* Refactored toxy tests slightly to reduce setup duplication.
* Added new tests.
* Updated test utils to log non-fatal errors for API tests.
New `rate-limit` Toxy tests passed locally.
Added new request unit test `should callback with error for 429 response`.
=> 138 rate limit tests

CHANGES.md, README.md, includes/writer.js, test/shallowbackup.js, test/writer.js
Retry restore batches on transient errors.
Re-enqueue batches on a transient failure.
Includes additional unit tests.
Fixes #138.
=> 138 retry restore batches on transient errors

Jenkinsfile, test/ci_compression.js, test/ci_largee2e.js, toxytests/toxy.js
Updated regression suite parameters.
* Extended timeout on compression test for slower containers.
* Fixed Toxy test flag check in Jenkinsfile.
* Changed Toxy poison settings to make tests faster and overcome limitations of poison implementation.
* Changed to 10 GB database for large backup.
Ran a Jenkins build using the new branch.
=> Fixed regression suite

CHANGES.md, Jenkinsfile, package.json
Prepared for 2.0.0 release.
* Changed the test filter for release builds to be the same as normal `master` builds - the slower tests are now run on a schedule.
* Updated the `CHANGES.md` for the version 2.0.0 release.
* Updated the `package.json` version to `2.0.0`
Automated tests are part of release cycle.
[Milestone 2.0](https://github.com/cloudant/couchbackup/milestone/1)
=> Prepare for v2.0.0

package.json
chore(package): update jsdoc to version 3.5.2
=> chore(package): update jsdoc to version 3.5.2

README.md
Clarified warning about attachments.
Updated top warning and added explanatory note.
Documentation change only.
Fixes #161 .
=> Updated attachment warning

Jenkinsfile
Updated version of DatabaseCompare to 1.0.1
CI passes.
N/A
=> Updated DB compare tool to version 1.0.1

CHANGES.md, includes/request.js, package.json, test/hooks.js
Merge into nodejs-cloudant 2.x feature branch.
Updated nodejs-cloudant dependency to 2.x-SNAPSHOT
Dependency change no new tests.
Start of #173
=> Update cloudant version

test/citestutils.js
Updated the behaviour of the resume tests to use `fs.watchFile` instead of `fs.watch`.
* Forced use of `fs.watchFile` to workaround issues with `fs.watch`.
For some reason `fs.watch` is no longer returning events from the docker executors on Jenkins. I haven't found the underlying reason for that change of behaviour, but we can switch to the polling form for the two tests that use it to unblock our CI.
* Made failure message more useful.
* Ensured tail unwatches log file in error cases.
N/A
=> Updated resume tests

CHANGES.md, Jenkinsfile, README.md, app.js, bin/couchbackup.bin.js, bin/couchrestore.bin.js, includes/backup.js, includes/config.js, includes/parser.js, includes/request.js, includes/restore.js, includes/shallowbackup.js, test/app.js, test/citestutils.js, test/config.js, test/parser.js, test/request.js, test/shallowbackup.js, test/spoolchanges.js, test/writer.js
Added support for using an IAM API key.
* Refactored to pass options dict instead of individual options:
* Access to the `iamApiKey` and `iamTokenEndpoint` override are required in the `request` class places, so rather than extended the internal function signatures to keep adding more parameters it makes sense to just pass the entire options dictionary around now.
* Added iamApiKey option to CLI and opts:
* Added `--iam-api-key` (`iamApiKey`) option.
* Added documentation for new option.
* Added validation for URL auth and iam-api-key:
* Prevent users supplying URL credentials and an IAM API key.
* Configured the nodejs-cloudant `iamauth` plugin when key supplied, default to the `cookieauth` plugin if …
=> Iam support

CHANGES.md, Jenkinsfile, README.md, app.js, bin/couchbackup.bin.js, bin/couchrestore.bin.js, includes/backup.js, includes/config.js, includes/error.js, includes/parser.js, includes/request.js, includes/restore.js, includes/shallowbackup.js, includes/spoolchanges.js, includes/writer.js, package.json, test/app.js, test/citestutils.js, test/config.js, test/hooks.js, test/parser.js, test/request.js, test/shallowbackup.js, test/spoolchanges.js, test/writer.js
Merge nodejs-cloudant 2.x branch to master.
The nodejs-cloudant 2.x changes have been reviewed previously and merged to the feature branch under PRs: #182 #184 #185 
The final change here is to set the nodejs-cloudant dependency in caed1950a1f8b9f383d7e65ec59f2c371567e010
`"@cloudant/cloudant": "^2.0.2"`
See #182 #184 #185 
CI testing was good.
This feature branch also tested cleanly when using the long running `couchbackup` tests.
Fixes #154 
Fixes #159 
Fixes #173
=> Nodejs cloudant 2

package.json
Updated eslint-config-semistandard to 12.0.1
Updated `package.json` min eslint versions to match eslint-config-semistandard to 12.0.1 and remove eslint-config-standard beta pin.
No new tests.
Fixes #197
Fixes #192
=> Greenkeeper/eslint config semistandard 12.0.1

.travis.yml, CHANGES.md, Jenkinsfile, README.md, package.json
Update engines in readiness for Argon EOL.
=> Update engines in readiness for Argon EOL

CHANGES.md, includes/backup.js, test/citestutils.js
Prevent duplicate execution of backup error callbacks.
=> Prevent duplicate execution of backup error callbacks

README.md
Add resume note to documentation.
Fixes #218.
=> Add resume note to documentation

CHANGES.md, package-lock.json, package.json
Incremented the minimum version of nodejs-cloudant (`@cloudant/cloudant`) to 2.2.0
No new tests, dependency change.
Fixes #207
=> 207 update cloudant min

CHANGES.md, README.md, app.js, includes/backup.js, includes/error.js, includes/restore.js, includes/shallowbackup.js, test/fatalerrors.js, test/shallowbackup.js
Added `HEAD` request to check the database exists before proceeding to backup.
Improved the error reporting by adding an existence check before proceeding to backup.
Refactored so the previously existing restore existence check
can be shared by backup and restore.
Exists function callback function now contains the backup/restore process.
Moved DB does not exist error code to common and updated messages according to case.
Moved the stream error handler registration earlier because of new callback.
Changed the internal backup/restore method signatures to take the db client object instead of URL.
Updated CHANGES.md.
Added test for existence check failure on backup.
Updated mocks with existence checks.
Fixed …
=> Added DB existence check for backup

CHANGES.md, package.json
Prepared for 2.3.0 release.
- [NEW] Check for database existence before starting backup. This provides for
better error messages for existence, authentication, and `_bulk_get` problems.
- [FIXED] Intermittent issues with multiple callbacks, particularly noticeable
when using Node.js 10.
- [FIXED] Issue where a success message could confusingly be output after a
fatal error.
- [UPGRADED] Increased nodejs-cloudant dependency minimum to 2.2.x.
No new tests, release PR.
https://github.com/cloudant/couchbackup/milestone/5
=> Prepared for 2.3.0 release

test/ci_compression.js, test/cli-e2e-tester.sh
Increased timeout for 2 GB compression backup test
Fixed comment and adjusted timeout to match for backup to compressed file.
Doubled timeout on 2 GB compression test because it has been timing out in the API mode on the slow docker executors.
Added manual acceptance test script for future use.
Changes to existing test timeouts. Temporarily enabled the test on this branch using the new timeout and it succeeded.
N/A - opened PR for CI failure.
=> Compression test timeout

CHANGES.md, app.js, package-lock.json, test/ci_concurrent_backups.js
Ensure concurrent database backups don't use the same default log file.
Create a new tmp file for each backup request.
Includes additional unit tests.
Fixes #110.
=> Fix concurrent backups

package-lock.json, package.json, test/app.js, test/ci_error.js, test/citestutils.js, test/config.js, test/logfilegetbatches.js, test/logfilesummary.js, test/parser.js, test/request.js, test/shallowbackup.js, test/spoolchanges.js, test/writer.js
Update eslint-plugin-node to the latest version.
=> Greenkeeper/eslint plugin node 7.0.1

Jenkinsfile
Added `gitTagAndPublish` to `Jenkinsfile`.
Replaced custom code with call to common `gitTagAndPublish` target.
Used common version parsing to identify release version for NPM publish.
- "No change"
- "No change"
Note that the release tagging was tested with nodejs-cloudant and this is a code copy from there.
- "No change"
=> Added gitTagAndPublish to Jenkinsfile

package-lock.json, package.json
Resolves #245 with version 4.0.1 of debug.
=> Update debug to 4.0.1 (Greenkeeper/debug 4.0.1)

CHANGES.md, includes/spoolchanges.js, includes/writer.js, package-lock.json, package.json
Use latest `@cloudant/cloudant` 3.x.x release.
Bump dependency in `package.json`.
Required small patch https://github.com/cloudant/couchbackup/commit/5d50a56c5b5c023587411b5d945d04747fe65c98 to ensure the Cloudant client was returning a stream when required.
No change.
No change.
Covered in existing test suite.
No change.
=> Use latest @cloudant/cloudant 3.x.x release

README.md
=> Shallow mode note.

CHANGES.md, includes/writer.js, package-lock.json, package.json
Upgraded `@cloudant/cloudant` to 4.x.
Fixes #264 
Replaces #269 
Upgrade `@cloudant/cloudant` to 4.xx to get Apache Nano 8.x.
Resolves issues with Apache Nano callbacks on large streams, but requires change to couchbackup writer to use stream events in place of callbacks.
- "No change"
- "No change"
- No new automated tests because a sufficiently large changes stream is required to expose the issue. Manual tests have been performed.
- "No change"
=> 264 nano stream nocallback

CHANGES.md, Jenkinsfile
Removed accidental `npm-cli-login` dependency introduced by publication automation.
Added `--no-save` argument to `npm install`.
- "No change"
- "No change"
- "No change"
=> Removed npm-cli-login dependency from publishing

package-lock.json, package.json
=> Update async 3.1.0

includes/request.js, includes/spoolchanges.js, package-lock.json, package.json, test/citestutils.js, test/fatalerrors.js
=> Greenkeeper/eslint plugin node 9.2.0

CHANGES.md, includes/request.js, package-lock.json, package.json
Upgraded `@cloudant/cloudant` dependency to version 4.2.2.
Includes change to set `errorOnNoCreds: false` for `cookieauth` plugin preventing 'credentials required' error when database URL does not contain credentials.
=> Set error on no creds false

CHANGES.md, README.md, package-lock.json, package.json
Added documentation about percent-encoding URL user info and upstream fix https://github.com/cloudant/nodejs-cloudant/pull/412.
* Updated `@cloudant/cloudant` to minimum 4.2.3
* Updated `README.md` with URL user info requirements and example.
* Updated `CHANGES.md`
- "No change"
- "No change"
- N/A documentation improvement
=> Document encoding in URL user info

package.json
* -> not necessary here
Fixes #326
- Updated versions in `package.json`:
* eslint `^5.15.1` -> `^6.8.0`
* eslint-config-standard  `^14.0.0` -> `^14.1.1`
- No change
- No change
- No change
=> Update eslint version

README.md
Fixes #335 
I extended the README with the TE circumstances regarding the buffer size.
- "No change"
- "No change"
- No new tests because only README was changed.
- "No change"
=> Add note for buffer size limits on TE

Jenkinsfile
Greenkeeper is retired by now.
I removed a method call that would have called when we are on a greenkeeper branch.
=> Remove gkLockfile from Jenkinsfile

CHANGES.md
This PR adds the CHANGES.md entry for #353 .
PR co-authored by @ricellis
=> Add CHANGES.md entry for queue pause behavior fix

package-lock.json, package.json
Bump @cloudant/cloudant from 4.3.0 to 4.4.0
Manual update and `npm install` for updating the `package-lock.json`
- No change
- No change
<!--
EITHER:
- No change
=> Bump @cloudant/cloudant from 4.3.0 to 4.4.0

CHANGES.md, Jenkinsfile, package.json
Update `package.json` engine requirement and Node.js version test matrix.
Fixes #361 
Update engine requirement to `"node": ">=12"`
- Use on unsupported/unmaintained Node.js versions will warn, but otherwise "No change"
- "No change"
Test with Node.js supported LTS versions `12` and `14` and current version `16`.
- "No change"
=> Engine update

includes/request.js, package-lock.json, package.json
Workaround axios performance issue.
Part of #357 
Update the `@ibm-cloud/cloudant` client to version `0.0.18`.
Ideally we would use core `2.14.1` with this fix: https://github.com/IBM/node-sdk-core/pull/158
- until we get that then this PR includes the same workaround.
- "No change"
- "No change"
Performance tests passing again after this change.
- "No change"
=> 357 perf fixes

app.js, includes/backup.js, includes/error.js, includes/request.js, includes/spoolchanges.js, test/request.js, test/spoolchanges.js, test/writer.js
Restore the original style error messages when using the new client.
Part of #357
Use an axios interceptor to manipulate the error messages before they reach the core so that we can include the http method, URL and error/reason information.
- This restores the error message style that was a limitation described in #365 
- "No change"
- Modified existing tests to assert correct messages.
- "No change"
=> 357 error msgs

includes/request.js, package-lock.json, package.json
Upgrade to `@ibm-cloud/cloudant` `0.0.19` and remove workarounds provided by new version and core.
Part of #357 
Update version to `0.0.19`
Remove `tough-cookie` dependency required by `@ibm-cloud/cloudant` now.
Remove performance workaround now provided by new `ibm-cloud-sdk-core` version (and indeed potentially new `axios` client version.
- "No change"
- New dependency versions remove transient dependency vulnerabilties.
- No new tests because existing tests cover functionality.
- Checked performance locally to ensure reversion of workaround did not degrade performance.
- "No change"
=> 357 cloudant node sdk 0.0.19

README.md
Update README to emphasize that target database for restore should be new and empty database.
Ref: #367
=> Update README to highlight restore database requirements

CHANGES.md, app.js, includes/backup.js, includes/error.js, includes/request.js, includes/shallowbackup.js, includes/spoolchanges.js, includes/writer.js, package-lock.json, package.json, test/ci_concurrent_backups.js, test/fatalerrors.js, test/hooks.js, test/request.js, test/shallowbackup.js, test/spoolchanges.js, test/writer.js
Migrate from `@cloudant/cloudant` to `@ibm-cloud/cloudant`
Fixes #357 
See PRs:
https://github.com/cloudant/couchbackup/pull/365
https://github.com/cloudant/couchbackup/pull/371
https://github.com/cloudant/couchbackup/pull/372
https://github.com/cloudant/couchbackup/pull/373
This PR is for moving the squashed/rebased changes from those PRs in the feature branch to `master`.
- "No change"
- "No change"
- Modified existing tests to pass with new:
- slight message changes for assertions
- updated mocks for HTTP method changes
- corrected parameters for some cases
- "No change"
=> 357 client feature

CHANGES.md, README.md, bin/couchbackup.bin.js, bin/couchrestore.bin.js, includes/config.js, includes/parser.js, test/config.js, test/parser.js
Add a quiet switch to reduce the output from couchbackup and couchrestore CLI commands.
Fixes #345
Split the `debug` instance between the summary messages (the original `couchbackup:backup` and `couchbackup:restore` namespaces) and the batch messages (new `couchbackup:backup:batch` and `couchbackup:restore:batch` namespaces.
Leave the summary message namespaces always `enabled:true` (as before).
Make the new namepsaces `enabled:true` by default to preserve existing behaviour, but make it settable via the quiet parameter.
- New `-q`, `--quiet` CLI parameter or `COUCH_QUIET` env var - note this is CLI only, the API does not log these messages (it sends the events instead so it is up to the user to handle/log events as desired).
- "No change"
- Added new tests for the quiet option:
- …
=> 345 add quiet switch

.secrets.baseline, CHANGES.md, includes/request.js, test/request.js
Fixes #417 
Use `decodeURIComponent` function when passing username and password to session authenticator.
- "No change"
- "No change"
Added test to verify that creds are properly handled during session request.
- "No change"
=> 417 fix credential special character encoding

package-lock.json, package.json
Remove unused dev deps `jsdoc` and `eslint-plugin-react`. Explicitly set dep on `ibm-cloud-sdk-core` and remove dep on `tough-cookie` (installed by core). Bump version of `mocha` to clean `npm audit` warning.
```
$ npx depcheck
npx: installed 126 in 7.371s
No depcheck issue
$ npm audit
=== npm audit security report ===
found 0 vulnerabilities
```
=> Update old dependencies, remove unused ones.

package.json
related to https://github.ibm.com/cloudant/integrations/issues/65
Email address `support@cloudant.com` has gone away and needs to be replaced.
Replace `support@cloudant.com` with `cldtsdks@us.ibm.com`.
=> Update support email address

CHANGES.md, package-lock.json, package.json
I moved `ibm-cloud-sdk-core` and `retry-axios` to the `peerDependencies` section of the `package.json` file, because those are installed from core or cloudant-node-sdk and no need for duplicates.
I used v12.22.10 of Node to regenerate the `package-lock.json` file, because with `16` the [builds failed](https://cloudant-sdks-jenkins.swg-devops.com/job/Main/job/couchbackup/job/use-peerDependencies/1/display/redirect).
I picked the minimum version based on these:
- The version for `ibm-cloud-sdk-core` in `@ibm-cloud/cloudant@0.0.25` is [2.17.10](https://github.com/IBM/cloudant-node-sdk/blob/553a6d1eb50e989aa84186ab8b3c6a2bea12e2ff/package.json#L40). 
- The version for `retry-axios` in  `ibm-cloud-sdk-core@2.17.10` is [^2.6.0](https://github.com/IBM/node-sdk-core/blob/3f19fce13f2b8a3d8c999b441b …
=> Use peer dependencies

.github/PULL_REQUEST_TEMPLATE.md, .secrets.baseline, Jenkinsfile, README.md
Primary branch check uses a hardcoded name.
Rename default branch without breaking CI.
Need to update check before renaming default branch.
Allow the use of any primary branch name by using the 
`expression { env.BRANCH_IS_PRIMARY }`
`when` condition check instead of specific branch name.
Update other links for rename to `main`.
- "No change"
- "No
- "No change"
=> Branch rename

test/citestutils.js
There has been a long time intermittent in asserting the compressed backup file. This seemed to be happen more frequently with the Mocha upgrade.
Related to #515 
Ensure waiting for CLI spwaned processes to close and the output stream to close if it is available.
Where there is a CLI backup process _and_ and output stream ensure that both are closed before calling back for the next stage of testing.
Before we waited only for the gzip process to close, but didn't wait for the backup process or the file stream to to finish. This meant sometimes the compressed file hadn't flushed and the assertion failed.
Waiting on all the respective processes and streams ensures everything is lined up before asserting.
This is achieved by counting callbacks and only calling back for real when we've had the …
=> test: fix intermittent failure

.secrets.baseline, Jenkinsfile
Add node 18 LTS to test axis
Fixes #520
=> ci: add node 18 LTS to test axes

SECURITY.md
Add vulnerability reporting policy to the repo similar to one [added to sdk](https://github.com/IBM/cloudant-node-sdk/pull/1067)
=> Add vulnerability reporting policy

Jenkinsfile
This change adds SonarQube Analysis to our pipeline.
Introduced the `SonarQube analysis` stage.
The analysis will not happen on `dependabot` generated branches.
- "No change"
- "No change"
- "No change"
=> Init SonarQube to pipeline

.secrets.baseline, Jenkinsfile, test/fatalerrors.js
Update to use the new build executors.
* rewrite Jenkinsfile to use new executor images
* declarative syntax for test phases
* run LTS tests on jnlp container
* run other node version tests in node containers
* use unique test report names
* install jenkins reporter once upfront
* add port option and unique ports for mock server and proxy
- "No change"
- "No change"
- Modified existing tests to allow specifying unique ports for mock server and proxy so that tests can run in parallel without conflicting.
- "No change"
=> ci: use new build executors

Jenkinsfile, README.md, package.json
- Remove Node 14 support
- Replace Node 19 with 20 in Jenkins test matrix
=> Remove Node 14 support

.github/PULL_REQUEST_TEMPLATE.md, .github/dco.yml, CHANGES.md, package.json
URL and config changes relating to repository transfer to `IBM` org.
* Add doc.yml DCO bot config
* Update PR template
* Update `CHANGES.md`
* Update repository URLs
- "No change"
- "No change"
- "No change"
=> Updates for repository transfer

Jenkinsfile, package-lock.json, package.json
Update version to 2.9.11-SNAPSHOT
Update version in `package.json` and `package-lock.json` to `2.9.11-SNAPSHOT`.
- "No change"
- "No change"
- "No change"
=> chore: update version to 2.9.11-SNAPSHOT

package-lock.json, package.json
Update version to 2.9.12-SNAPSHOT
Update version in `package.json` and `package-lock.json` to `2.9.12-SNAPSHOT`.
- "No change"
- "No change"
- "No change"
=> chore: update version to 2.9.12-SNAPSHOT

package-lock.json
build(deps): upgrade tough-cookie to 4.1.3 (package-lock)
build(deps): upgrade tough-cookie to 4.1.3 (package-lock)
- "No change"
- "No change"
- "No change"
=> build(deps): upgrade tough-cookie to 4.1.3 (package-lock)

package-lock.json, package.json
chore: update version to 2.9.13-SNAPSHOT
chore: update version to 2.9.13-SNAPSHOT
- "No change"
- "No change"
- "No change"
=> chore: update version to 2.9.13-SNAPSHOT

package-lock.json, package.json
chore: update version to 2.9.14-SNAPSHOT
chore: update version to 2.9.14-SNAPSHOT
=> chore: update version to 2.9.14-SNAPSHOT

.secrets.baseline, Jenkinsfile, test/ci_event.js, test/citestutils.js, test/test_process.js
Modernize `testBackup` to use more up-to-date Node features for robustness.
Part of i272.
* Create a `test_prcess.js` for handling CLI processes
* Use pipelines and promises to coordinate the backup processes
The new approach seems to expose some timing issue on resume tests where it tries to restore before the database is available. I think this will resolve as we start to do more of the modernization.
- "No change"
- "No change"
- Modified existing tests as outlined above.
- Added new logging in TestProcess so we can debug tests more easily.
=> Modernize testBackup code

test/ci_resume.js, test/citestutils.js, test/test_process.js
Modernize `testRestore` to use more up-to-date Node features for robustness.
Part of i272.
* Use the `TestProcess` added in #621 for CLI restores
* Add decrypt and gunzip processes
* Use pipelines and promises to coordinate the restore processes
Note the failing tests from #621 remain, but a third PR will be following that will resolve those.
- "No change"
- "No change"
- Modified existing tests as outlined above.
- Introduced a new paramter to be able to suppress an expected error during restores from corrupted files.
- Added new logging in clitestutils so we can debug tests more easily.
=> Modernize testRestore code

test/test_process.js
Add mode to testProcess.
Add a mode to make the duplex wrapping the test child process be either a readable, writable or both depending on the needs of the executing child process.
Adapt the child process `stdio` and the `Duplex.from` args as necessary based on the nature of the child process as either readable/writable/duplex.
- "No change"
- "No change"
- Modified existing tests, ran quite a few builds, no sign of premature stream close issue.
- Failing tests are the existing failures in `test-modernization` that will be resolved by #630.
- "No change"
=> test: add mode to testProcess

.secrets.baseline, test/app.js, test/compare.js, test/config.js, test/fatalerrors.js, test/logfilegetbatches.js, test/logfilesummary.js, test/parser.js, test/request.js, test/shallowbackup.js, test/spoolchanges.js, test/writer.js
Modernize unit test cases:
- Return promises and convert functions to async
- Remove mocha `done` callback
=> Modernize unit tests

.secrets.baseline, test/app.js, test/ci_basic.js, test/ci_compression.js, test/ci_concurrent_backups.js, test/ci_e2e.js, test/ci_encryption.js, test/ci_error.js, test/ci_event.js, test/ci_largee2e.js, test/ci_resume.js, test/citestutils.js, test/compare.js, test/config.js, test/fatalerrors.js, test/hooks.js, test/logfilegetbatches.js, test/logfilesummary.js, test/parser.js, test/request.js, test/shallowbackup.js, test/spoolchanges.js, test/test_process.js, test/writer.js
Merge `test-modernization` to `main`.
Part of i270.
The majoirty of this work was previously reviewed in:
* #621 
* #623 
* #624 
* #628 
* #630
This PR is simply to put it in `main` and has resolved any conflicts.
There is one additional commit https://github.com/IBM/couchbackup/pull/634/commits/8ad7f22db6883355331f572650cef8a52c321a40 to remove some osbolete callbacks.
- "No change"
- "No change"
- Modified existing tests as part of modernization.
- "No change"
=> Test modernization

package-lock.json, package.json
Update version to 2.9.15-SNAPSHOT
Update `@cloudant/couchbackup` in `package.json` and `package-lock.json` to version `2.9.15-SNAPSHOT`
=> chore: update version to 2.9.15-SNAPSHOT

Jenkinsfile
Reenable the test matrix branches for Node 20.
Fixes #583 
Revert the when condition added in a50ba7547bea142787618a3409cd1f21db00a608 as the work in #634 has resolved the test issues.
- "No change"
- "No change"
- Modified existing tests to reenable branches using Node 20.
- "No change"
=> ci: reenable Node 20 matrix tests

includes/transforms.js, test/transforms.js
Add `chunkMapFn` and `postWriteFn` to the `DelegateWritable`.
Fixes part of i259
Add `chunkMapFn` and `postWriteFn` to the `DelegateWritable`.
* `chunkMapFn` enables the `DelegateWriter` to map objects to their string form for writing. This simplifies passing batch objects down the pipeline.
* `postWriteFn` simplifies maintaining compatibility by e.g. having a place to emit an event when an individual write completes when a `DelegateWritable` is at the end of the pipeline.
- "No change"
- "No change"
- Added new tests to increase the parameterized combinations for `DelegateWritable`.
- "No change"
=> refactor: add chunkMapFn and postWriteFn

includes/parser.js, test/hooks.js, test/request.js
chore: resolve lint warnings
Fixes part of i312.
Resolve linter warnings for `object-shorthand` (remaining warnings are covered in other branches).
- "No change"
- "No change"
- No new tests because only changing code style to resolve linting.
- "No change"
=> chore: resolve lint warnings

package-lock.json, package.json
Update version to `2.9.17-SNAPSHOT`
Update `package.json` and `package-lock.json` to version `2.9.17-SNAPSHOT`
=> chore: update version to 2.9.17-SNAPSHOT

includes/liner.js
Improve the `Liner` implementation in `modernization` branch to respect back-pressure. 
Part of i330.
Change from a `Transform` implementation to a `Duplex`. Transforms are well suited to 1:1 changes, but the nature of the Liner is different. It may take many chunks being written to get an entire line (many:1) or it may produce many lines from a large chunk of a file (1:many). Applying back pressure via the `_transform` `callback` is challenging when accounting for those different situations.
Instead use a `PassThrough` as the writable side of the `Duplex` and wrap that stream in the `readline` interface. If that streams buffers are full it passes back-pressure upstream to the file via the `write`/`callback` delegation.
The readable side of the `Duplex` is an array of lines that is …
=> fix: handle back-pressure in Liner

includes/backup.js, includes/spoolchanges.js, test/spoolchanges.js
Use separate promises for the changes spooling and backup fetching.
Fixes i332
We had attempted to solve #113 by putting the spooling of changes at the start of the pipeline and running straight through to backing up. The problem with this approach is that downstream back-pressure holds up the fetching of changes. This spreads the window over which couchbackup gets the list of IDs to backup over a wider window than previously. The additional time it takes to reach the end of the changes feed makes it possible for changes to be written faster than they can be backed up and potentially create a never-ending backup.
This PR reverts to the existing approach of completing the spooling of changes and then commencing the document fetches via `_bulk_get`.
* Modify `spoolchanges` to use a …
=> fix: revert to complete spooling before backup

includes/transforms.js
Apply high water marks to the mapping streams.
Fixes part of i330
Override the default temporarily when we create mapping streams.
`Duplex.from` does not honour `highWaterMark` configuration. Instead get the current default high water mark, set a new high water mark appropriate for our use case of minimizing the memory footprint, then reset the original high water mark.
Also change the mapping streams to extend a new `DuplexMapper` so we don't have to use the same workaround multiple times.
- "No change"
- "No change"
- No new tests because the pipeline is covered by existing tests.
- "No change"
=> fix: high water marks in mapping streams

includes/request.js, test/citestutils.js, test/compare.js, test/hooks.js
- Added `sharedClient` function that's used in hooks and compare test files.  
- Added `newSimpleClient` in `includes/request` that initializes a client with auth handling.
- Updated `newClient` in `includes/request` to init with new `newSimpleClient` function
fixes i296
No new tests
=> test: shared client access in tests

Jenkinsfile
With https://github.com/IBM/couchbackup/pull/697 merged, this work updates the urls in Jenkins to take advantage of the test hooks being able to use IAM auth.
fixes i296
=> ci: update test URL env vars

bin/couchbackup.bin.js, bin/couchrestore.bin.js
With the recent merge of #702  and existing changes in modernization, there is nowhere left where `error` events are emitted.  This work removes the `on('error'...` blocks in the backup and restore bin scripts.
fixes i314
=> fix: remove error event handlers in backup and restore bin scripts

Jenkinsfile
Disable debug from the SQ scan as it overwhelms the build logs.
Fixes: part of i347
Remove `-X` flag from sonar scanner command.
- "No change"
- "No change"
- "No change"
=> ci: disable SQ debug

Jenkinsfile
When reviewing build logs, Rich came across `Error: write EPIPE` in a Node 20 IAM build.
As we continue to build the modernization branch to verify its stability, this work adds a Jenkins stage to check the test logs for this EPIPE error.
related to i339
=> ci: check test suite logs for EPIPE error

Jenkinsfile, package.json
Update CI release process.
Fixes part of i303
* Resolve `package.json` publish warnings
* Split `Publish` stage into 3 parts
1.  `Tag and GH release` - for `main` branch call `gitTagAndPublish`
* Make a tag for the build from the `package.json` version
* Push the tag if it is a release version (otherwise it is a dry run)
* Make a matching GH release if it is a release version
1. `NPM snapshot publish` - for `main` branch
* Append a build number to the snapshot version
* Push the `snapshot` tag build to `npm`
1. `NPM publish` - for tag builds
* Do the release `npm publish`
* This will require a CI change to discover tags.
- "No change"
- "No change"
- N/A build or packaging only changes - tested publish process with snapshots
- "No change"
=> ci: update release process

package-lock.json, package.json
Update version to 2.10.0-SNAPSHOT
Fixes part of i348
Update `package.json` and `package-lock.json` to version `2.10.0-SNAPSHOT`
- "No change"
- "No change"
- "No change"
=> chore: update version to 2.10.0-SNAPSHOT

Jenkinsfile
Fix snapshot version format
Fixes part of i303
Change the build identifier from `.N` to `-N` so that on release builds where there is no `-SNAPSHOT` suffix we still get a valid identifier.
- "No change"
- "No change"
- "No change"
=> build: fix snapshot version format

package-lock.json, package.json
[chore: update version to 2.10.1-SNAPSHOT](https://github.com/IBM/couchbackup/commit/cc70b67bb9c0b52c7b4ddd348cb36df1f581b919)
UUpdate version to 2.10.1-SNAPSHOT in package files.
- "No change"
- "No change"
- "No change"
=> chore: update version to 2.10.1-SNAPSHOT

Jenkinsfile
Adjust executor resources.
Fixes part of i350
Align resources with scaling convention, using size 4 for Node version axes and size 5 for the LTS that also runs the agent as well as 2 test axes.
- "No change"
- "No change"
- "No change"
=> ci: adjust resource templates

CHANGES.md, README.md
Fixes #726
* Fix errors from #726.
* Fix some typos.
* Clean up a lot of Vale warnings.
- "No change"
- "No change"
- N/A docs
- "No change"
=> docs: README updates

CHANGES.md, app.js, includes/restoreMappings.js, package-lock.json, package.json, test/compare.js, test/restore.js
Changes for SDK 0.9.0 version.
Fixes i355
Renames required by breaking changes in `0.9.0` SDK.
- "No change"
- "No change"
- Modified existing tests for renames.
- "No change"
=> fix: SDK 0.9.0 migration

Jenkinsfile
Node's 22 (Upcoming LTS ) ws release on Apr 24 and now is "current". This PR switches "current" node in Jenkins test matrix from 21 to 22.
Replace node 21 with 22 in QA stage
=> chore(ci): update for current from node 21 to 22

package-lock.json, package.json
Regular update to SNAPSHOT version
=> chore: update version to 2.10.2-SNAPSHOT

package-lock.json, package.json
Bump peerDependencies to the latest ibm-cloud-sdk-core that moved major version from 4.x to 5.x and also bump axios to match core and for CVE on axios < 1.7.4
Update `package.json`, run `npm i --package-lock-only` to sync `package-lock.json`
- "No change"
CI should come green
=> build(peer-deps): bump axios and ibm-cloud-sdk-core

package-lock.json, package.json
=> chore: update version to 2.10.3-SNAPSHOT

test/ci_e2e.js
Add assertions to validate attachment content.
Follow up to #760 
* Add a call to `getAttachment`
* Pipe the content into a `Writable`
* Assert the content matches the expected.
- "No change"
- "No change"
- Modified existing tests because the test compared the files, but didn't check the content in the database. This extra assertion validates that the base64 content is actually the correct attachment.
- "No change"
=> test: validate attachment content

package-lock.json, package.json
=> chore: update version to 2.11.1-SNAPSHOT

Jenkinsfile, README.md, package-lock.json, package.json
fixes i374
Prepare the default agent to Node 22.
Update LTS to Node 22.
Add `Node 20x` step with `container('node20')`.
Remove `Node 22x` step.
- "No change"
- "No change"
- "No change"
=> build: update for Node 22 LTS

package-lock.json, package.json
=> chore: update version to 2.11.2-SNAPSHOT

package-lock.json, package.json
=> chore: update version to 2.11.3-SNAPSHOT

package-lock.json, package.json
chore: update version to 2.11.4-SNAPSHOT
Update version to `2.11.4-SNAPSHOT`
- "No change"
- "No change"
- "No change"
=> chore: update version to 2.11.4-SNAPSHOT

package-lock.json, package.json
chore: update version to 2.11.5-SNAPSHOT
Update version to 2.11.5-SNAPSHOT
- "No change"
- "No change"
- "No change"
=> chore: update version to 2.11.5-SNAPSHOT

package-lock.json, package.json
chore: update version to 2.11.6-SNAPSHOT
Update version to 2.11.6-SNAPSHOT
- "No change"
- "No change"
- "No change"
=> chore: update version to 2.11.6-SNAPSHOT

package-lock.json, package.json
chore: update version to 2.11.7-SNAPSHOT
Update version to 2.11.7-SNAPSHOT
- "No change"
- "No change"
- "No change"
=> chore: update version to 2.11.7-SNAPSHOT

.secrets.baseline, examples/README.md, examples/cos-sdk/README.md, examples/cos-sdk/cos-restore-file.js, examples/cos-sdk/cos-restore-stream.js
Added new example code into `examples` folder.
- No change
- No change
- No new tests because it is example code.
- No change
=> IBM COS restore examples pr

examples/cos-s3/README.md, examples/cos-s3/package.json, examples/cos-s3/s3-backup-file.js, examples/cos-s3/s3-backup-stream.js, examples/cos-s3/s3-restore-file.js, examples/cos-s3/s3-restore-stream.js, examples/cos-sdk/README.md, examples/cos-sdk/cos-backup-file.js, examples/cos-sdk/cos-backup-stream.js, examples/cos-sdk/cos-restore-file.js, examples/cos-sdk/cos-restore-stream.js
Added new example code into `examples` folder.
- No change
- No change
- No new tests because it is example code.
- No change
=> Aws s3 restore examples

package-lock.json, package.json
chore: update version to 2.11.8-SNAPSHOT
Update version to 2.11.8-SNAPSHOT
- "No change"
- "No change"
- "No change"
=> chore: update version to 2.11.8-SNAPSHOT

Jenkinsfile
Add detect secrets stage to build.
Fixes part of i483
Add new `Jenkinsfile` stage.
- "No change"
- "No change"
- "No change"
=> ci: add detect secrets stage

Jenkinsfile
Adjust SQ stage conditions
Fixes: i447
Enable the SQ stage for PR builds.
- "No change"
- "No change"
- "No change"
=> ci: adjust SQ stage conditions

Jenkinsfile
Add the `anyOf` missed by #875 
Fixes i447
* Add `anyOf` around `changesRequest` and primary branch check (it can't be both!)
- "No change"
- "No change"
- "No change"
=> ci: fix sq stage condition
